spring:
  application:
    name: financas-pessoais
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:financas}
    username: ${DB_USER:financas}
    password: ${DB_PASSWORD:financas}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
